---
title: "A Grammar for Graphics"
subtitle: "A collection of terms and concepts to declare data visualization systematically"
author: "Otho Mantegazza"
editor_options:  
  chunk_output_type: console
---

## {background-image="img/minard-russian-campaign.png" background-size="contain" background-repeat="no-repeat"}

## Can you Describe a Graph?

:::: {.columns}

::: {.column width="50%"}

If we find a way to describe graphs systematically, then we can design and develop them more easily.

Most technical graphs can be declared with a system of rules called "Grammar of Grapihcs".

This system of rules is the basis for many data visualization packages, such as [ggplot2](https://ggplot2.tidyverse.org/), [Seaborn](https://seaborn.pydata.org/) and [Altair](https://altair-viz.github.io/).

:::

::::

## {background-image="img/layered-grammar.svg" background-size="contain" background-repeat="no-repeat"}

::: {.caption .rev .absolute right=850 bottom=70}

[A LAYERED GRAMMAR OF GRAPHICS](https://vita.had.co.nz/papers/layered-grammar.html)

:::

## A Grammar for Graphics

:::: {.columns}

::: {.column width="50%"}

The "Grammar of Graphics" was developed by [Leeland Wilkinson](https://en.wikipedia.org/wiki/Leland_Wilkinson).

It was later [extended](https://vita.had.co.nz/papers/layered-grammar.html) by Hadley Wickham, who started encoding it in the R package [ggplot2](https://ggplot2.tidyverse.org/).

::: 

:::: 

## A Grammar for Graphics

:::: {.columns}

::: {.column width="70%"}

The layered grammar of grapics states that:

- A default dataset and set of mappings from variables to aesthetics.
- One or more layers, with each layer having one geometric object, one statistical transformation, one position adjustment, and optionally, one dataset and set of aesthetic mappings.
- One scale for each aesthetic mapping used.
- A coordinate system.
- The facet specification.

:::
 
::::

## Aesthetics

The word aesthetic is derived from the Ancient Greek αἰσθητικός (aisthētikós, "perceptive, sensitive, pertaining to sensory perception"), which in turn comes from αἰσθάνομαι (aisthánomai, "I perceive, sense, learn") and is related to αἴσθησις (aísthēsis, "perception, sensation").

https://en.wikipedia.org/wiki/Aesthetics#Etymology

## Let's Describe Graphs

:::: {.columns}

::: {.column width="50%"}

Let's describe three historical graphs in terms of the Grammar of Graphics.

1. How are data mapped to aesthetics?
2. What statistical transformation is applied?
3. Which geometric object is used?
4. What is the coordinate system?
5. Are the data splut in facets?

- Lineplot
- Semichart
- Nightingale Radial

:::
 
::::
