project:
  title: "Data Visualization for Scientists"
  preview:
    port: 4200
  output-dir: docs
  render: 
    - "*.qmd"
  
format:
  revealjs:
    theme: [default, style/custom.scss]
    template-partials:
      - style/title-slide.html
    echo: true
    footer: "[< HOME](../index.html)"

knitr:
  opts_chunk: 
    dev: svglite

